### ISSUE TITLE
panic while enabling sidecar injection on new namespace

### ISSUE THREAD

**Issue by DelusionalOptimist** [meshery/meshery-istio#279]
**Description**
When trying to apply the "Automatic Sidecar Injection" operation on a namespace, the adapter panics.

**Expected Behavior**
The adapter should not panic and create the namespace if it doesn't exist because the general flow for anyone who will be deploying an application will be:
* create an ns
* enable sidecar injection on it
* deploy app

**Logs**
```
time="2021-09-21T09:47:51Z" level=info msg="Applying operation label-namespace" app=istio-adaptor
panic: interface conversion: error is *errors.StatusError, not *errors.Error

goroutine 93 [running]:
github.com/layer5io/meshkit/errors.GetCode(0x21e9ca0, 0xc0004b3220, 0xc00083be20, 0x135814e)
        /go/pkg/mod/github.com/layer5io/meshkit@v0.2.21/errors/errors.go:90 +0xd1
github.com/layer5io/meshkit/logger.(*Logger).Error(0xc00012c298, 0x21e9ca0, 0xc0004b3220)
        /go/pkg/mod/github.com/layer5io/meshkit@v0.2.21/logger/logger.go:57 +0xaa
github.com/layer5io/meshery-adapter-library/adapter.(*Adapter).StreamErr(...)
        /go/pkg/mod/github.com/layer5io/meshery-adapter-library@v0.1.22/adapter/stream.go:25
github.com/layer5io/meshery-istio/istio.(*Istio).ApplyOperation.func6(0xc000226d20, 0xf, 0xc000226d18, 0x8, 0xc000226d30, 0xc, 0x0, 0x0, 0x0, 0xc0005d2660, ...)
        /build/istio/istio.go:136 +0x199
created by github.com/layer5io/meshery-istio/istio.(*Istio).ApplyOperation
        /build/istio/istio.go:127 +0x696
```

**Enviroment:**
 - OS: Linux
 - Browser: Any
 - Adapter-version: v0.5.16
 - Deployment: Out of cluster (docker & minikube)

---
[Optional] **To Reproduce**
1. Go to adapter's page
2. Click on the 'namespace' box and create a new namespace
3. Apply the "automatic sidecar injection" operation
4. See panic

**Comment by DelusionalOptimist** [comment]
@Shreyas220 is this something you can look at?

**Comment by Shreyas220** [comment]
yeh sure

**Comment by Shreyas220** [comment]
@DelusionalOptimist i cant reproduce this error 
![image](https://user-images.githubusercontent.com/55346934/134224431-6b59e074-1d71-41e8-ba1d-21e42ebf6295.png)
![image](https://user-images.githubusercontent.com/55346934/134224473-484522b2-8e09-4e3e-a082-02e8b28a1d6f.png)

**Comment by DelusionalOptimist** [comment]
@Shreyas220 please try with a namespace that doesn't exist in your cluster i.e, something other than "default".

**Comment by DelusionalOptimist** [comment]
@Shreyas220 still not able to reproduce this bug?

**Comment by Shreyas220** [comment]
> @Shreyas220 still not able to reproduce this bug?

yeh I was able to reproduce this

**Comment by DelusionalOptimist** [comment]
ok. I think this bug is arising because of logging a non meshkit error using the meshkit logger, if that helps.
